### ISSUE TITLE
Wrong offset on orientation change

### ISSUE THREAD

**Issue by v-yatsevich** [harryzjm/SMWaterFlowLayout#1]
For example, I have iPad, on portrait orientation, there are 3 lines, on landscape orientation are 4. When I scroll a bit from the beginning of the collection view and change orientation I see a big displacement of items and the far from the beginning I change orientation - the bigger displacement I have (shift if more than a screen)

**Comment by v-yatsevich** [comment]
I fix it with this code

```
guard let layout = self.collectionView.layout as? SMWaterFlowLayout else {
    return
}
if self.linesCount == 0 {
    self.linesCount = layout.lineCount
    return
}
if self.linesCount == layout.lineCount {
    return
}
self.collectionView.contentOffset.y *= CGFloat(self.linesCount) / CGFloat(layout.lineCount)

self.linesCount = layout.lineCount
```

but I don't know where exactly I should insert code like this in layout class

**Comment by harryzjm** [comment]
@AntiVIRUZ Thank you, I will test it, and fix it.

**Comment by harryzjm** [comment]
@AntiVIRUZ  I fix it, please check new release.
